name: docker
on:
  push:
    branches:
      - develop_account_page
    tags:
      - v*
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_MONGODB_URI: ${{secrets.MONGODB_URI}}
          envkey_MONGODB_URI_LOCAL: ${{secrets.MONGODB_URI_LOCAL}}
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          envkey_GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          file_name: .env
      -
        name: display1 folder structure
        run: ls -la
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: display2 folder structure
        run: ls -la
      - 
        name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        env:
          MONGODB_URI: ${{secrets.MONGODB_URI}}
          MONGODB_URI_LOCAL: ${{secrets.MONGODB_URI_LOCAL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      -
        name: Build and push backend
        uses: docker/build-push-action@v3    
        with:
          context: ./api
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/back-end-test:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_TOKEN }}
            
      -
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./client
          push: true
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/front-end-test:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MY_TOKEN }}
